version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: cd server && yarn
  test:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: cd server && yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - test
