name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd server && yarn
      # - run: npm run build --if-present
      - run: apt install redis-server
      - run: redis-server&
      - run: cd server && yarn test
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          PORT: ${{secrets.PORT}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
          FRONTEND_HOST: ${{secrets.FRONTEND_HOST}}
          URL: ${{secrets.URL}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
